### ISSUE TITLE
Pack UV button/option

### ISSUE THREAD

**Issue by MattFagan** [mio3io/mio3_uv#2]
Wonderful job with this Add-on for Blender. I was just a bit confused why there wasn't a Pack UV button anywhere in the add-on.

It would be a nice thing to have, so I don't have to navigate outside of the Add-on when working with UV's to do packing as the last measure. If this is something under going work, then please ignore this issue and keep up the great work!

**Comment by mio3io** [comment]
Personally, I use UV Packmaster for packing, so I didn't include it in the add-on. Also, Blender's built-in operator "Pack Islands" is slow, but it is quite practical.

I have tried to make a prototype once, but it seems that it is not easy to make something practical.

I may try it again in the future, but it is a low priority because there are other features I want to implement. Sorry.
